"""Stable public SDK surface for reversible action transactions.

Import canonical contract names from here; module paths below are
implementation detail and may reorganize.
"""

from agent.effects.models import (
    COMPENSATION_FIDELITIES,
    EFFECT_PHASES,
    ELIGIBILITY_CODES,
    FAILURE_POLICIES,
    RECONCILE_DISPOSITIONS,
    TRANSACTION_STATUSES,
    ActionTransaction,
    CommitOutcome,
    CommitRequest,
    CompensationRequest,
    CompensationResult,
    EffectContext,
    EffectPreview,
    EffectSemantics,
    EffectTransaction,
    ImmutableRecordError,
    NormalizedEffect,
    PreparedEffect,
    ReconciliationResult,
    RevisionConflict,
    RevisionEdge,
    RevisionNode,
    TransactionEvent,
    TransactionRevision,
    TransactionSnapshot,
    TransactionStoreError,
    VerificationResult,
    canonical_json,
    content_hash,
)
from agent.effects.authority import (
    ApprovalBinding,
    ApprovalConsumption,
    ApprovalIdentity,
    build_action_context,
    consume_bound_approval,
    request_bound_approval,
)
from agent.effects.registry import (
    AdapterContractError,
    AdapterDescriptor,
    EffectAdapter,
    EffectAdapterRegistry,
    default_effect_adapter_registry,
    get_effect_adapter,
    register_effect_adapter,
)
from agent.effects.store import TransactionStore

__all__ = [
    "COMPENSATION_FIDELITIES",
    "EFFECT_PHASES",
    "ELIGIBILITY_CODES",
    "FAILURE_POLICIES",
    "RECONCILE_DISPOSITIONS",
    "TRANSACTION_STATUSES",
    "ActionTransaction",
    "AdapterContractError",
    "AdapterDescriptor",
    "ApprovalBinding",
    "ApprovalConsumption",
    "ApprovalIdentity",
    "CommitOutcome",
    "CommitRequest",
    "CompensationRequest",
    "CompensationResult",
    "EffectAdapter",
    "EffectAdapterRegistry",
    "EffectContext",
    "EffectPreview",
    "EffectSemantics",
    "EffectTransaction",
    "ImmutableRecordError",
    "NormalizedEffect",
    "PreparedEffect",
    "ReconciliationResult",
    "RevisionConflict",
    "RevisionEdge",
    "RevisionNode",
    "TransactionEvent",
    "TransactionRevision",
    "TransactionSnapshot",
    "TransactionStore",
    "TransactionStoreError",
    "VerificationResult",
    "build_action_context",
    "canonical_json",
    "consume_bound_approval",
    "content_hash",
    "default_effect_adapter_registry",
    "get_effect_adapter",
    "register_effect_adapter",
    "request_bound_approval",
]
