"""Stable public SDK surface for reversible action transactions.

Import canonical contract names from here; module paths below are
implementation detail and may reorganize.
"""

from agent.effects.models import (
    COMPENSATION_FIDELITIES,
    EFFECT_PHASES,
    ELIGIBILITY_CODES,
    FAILURE_POLICIES,
    RECONCILE_DISPOSITIONS,
    TRANSACTION_STATUSES,
    ActionTransaction,
    CommitOutcome,
    CommitRequest,
    CompensationRequest,
    CompensationResult,
    EffectBlocked,
    EffectContext,
    EffectPreview,
    EffectSemantics,
    EffectTransaction,
    ImmutableRecordError,
    NormalizedEffect,
    PreparedEffect,
    ReconciliationResult,
    RevisionConflict,
    RevisionEdge,
    RevisionNode,
    TransactionEvent,
    TransactionRevision,
    TransactionSnapshot,
    TransactionStoreError,
    VerificationResult,
    canonical_json,
    content_hash,
)
from agent.effects.authority import (
    ApprovalBinding,
    ApprovalConsumption,
    ApprovalIdentity,
    build_action_context,
    consume_bound_approval,
    request_bound_approval,
)
from agent.effects.context import (
    TransactionExecutionContext,
    set_runtime_coordinator,
    transaction_context,
    transaction_context_from_runtime,
)
from agent.effects.coordinator import (
    CommitResult,
    CompensationOutcome,
    PreviewResult,
    ReconcileResult,
    TransactionCoordinator,
)
from agent.effects.eligibility import (
    CompensationPlan,
    UndoEligibility,
    eligibility_for_effect,
    eligibility_for_transaction,
    plan_compensation,
)
from agent.effects.recovery import (
    project_transaction_status,
    recover_transactions,
    recover_transactions_at_startup,
)
from agent.effects.registry import (
    AdapterContractError,
    AdapterDescriptor,
    EffectAdapter,
    EffectAdapterRegistry,
    default_effect_adapter_registry,
    get_effect_adapter,
    register_effect_adapter,
)
from agent.effects.store import TransactionStore

__all__ = [
    "COMPENSATION_FIDELITIES",
    "EFFECT_PHASES",
    "ELIGIBILITY_CODES",
    "FAILURE_POLICIES",
    "RECONCILE_DISPOSITIONS",
    "TRANSACTION_STATUSES",
    "ActionTransaction",
    "AdapterContractError",
    "AdapterDescriptor",
    "ApprovalBinding",
    "ApprovalConsumption",
    "ApprovalIdentity",
    "CommitOutcome",
    "CommitRequest",
    "CommitResult",
    "CompensationOutcome",
    "CompensationPlan",
    "PreviewResult",
    "ReconcileResult",
    "TransactionCoordinator",
    "TransactionExecutionContext",
    "CompensationRequest",
    "CompensationResult",
    "EffectAdapter",
    "EffectAdapterRegistry",
    "EffectBlocked",
    "EffectContext",
    "EffectPreview",
    "EffectSemantics",
    "EffectTransaction",
    "ImmutableRecordError",
    "NormalizedEffect",
    "PreparedEffect",
    "ReconciliationResult",
    "RevisionConflict",
    "RevisionEdge",
    "RevisionNode",
    "TransactionEvent",
    "TransactionRevision",
    "TransactionSnapshot",
    "TransactionStore",
    "TransactionStoreError",
    "UndoEligibility",
    "VerificationResult",
    "build_action_context",
    "eligibility_for_effect",
    "eligibility_for_transaction",
    "plan_compensation",
    "canonical_json",
    "consume_bound_approval",
    "content_hash",
    "default_effect_adapter_registry",
    "get_effect_adapter",
    "project_transaction_status",
    "recover_transactions",
    "recover_transactions_at_startup",
    "register_effect_adapter",
    "request_bound_approval",
    "set_runtime_coordinator",
    "transaction_context",
    "transaction_context_from_runtime",
]
